language: c++
sudo: false

addons:
  apt:
    sources:
    - ubuntu-sdk-team

addons:
  apt:
    packages:
    - ubuntu-sdk

cache:
  directories:
  - $HOME/qtgoodies

before_install: true
install: true
before_script: true

script:
  - ls
  - sh -c "qmake CONFIG+=release demo/QtGoodiesDemo/QtGoodiesDemo.pro && make"
