language: cpp

addons:
  apt:
    sources:
    - ubuntu-sdk-team

addons:
  apt:
    packages:
    - ubuntu-sdk

script:
  - sh -c "qmake CONFIG+=release demo/QtGoodiesDemo/QtGoodiesDemo.pro && make"
