language: python

addons:
  apt:
    sources:
    - ubuntu-sdk-team

addons:
  apt:
    packages:
    - ubuntu-sdk

script:
  - ls
  - echo "tell me this is working"
  - sh -c "qmake CONFIG+=release demo/QtGoodiesDemo/QtGoodiesDemo.pro && make"
