sudo: false

addons:
  apt:
    sources:
    - ubuntu-sdk-team

addons:
  apt:
    packages:
    - ubuntu-sdk

language: cpp

before_script: true

script:
  - qmake demo/QtGoodiesDemo/QtGoodiesDemo.pro && make

